INSERT INTO ingredients (id, name, default_unit) VALUES
    (gen_random_uuid(), 'Мука пшеничная', 'г'),
    (gen_random_uuid(), 'Сахар', 'г'),
    (gen_random_uuid(), 'Соль', 'г'),
    (gen_random_uuid(), 'Масло сливочное', 'г'),
    (gen_random_uuid(), 'Масло растительное', 'мл'),
    (gen_random_uuid(), 'Яйца куриные', 'шт'),
    (gen_random_uuid(), 'Молоко', 'мл'),
    (gen_random_uuid(), 'Сметана', 'г'),
    (gen_random_uuid(), 'Кефир', 'мл'),
    (gen_random_uuid(), 'Творог', 'г'),
    (gen_random_uuid(), 'Сыр твёрдый', 'г'),
    (gen_random_uuid(), 'Курица филе', 'г'),
    (gen_random_uuid(), 'Говядина', 'г'),
    (gen_random_uuid(), 'Свинина', 'г'),
    (gen_random_uuid(), 'Картофель', 'г'),
    (gen_random_uuid(), 'Морковь', 'г'),
    (gen_random_uuid(), 'Лук репчатый', 'г'),
    (gen_random_uuid(), 'Чеснок', 'зуб'),
    (gen_random_uuid(), 'Помидоры', 'г'),
    (gen_random_uuid(), 'Огурцы', 'г'),
    (gen_random_uuid(), 'Капуста белокочанная', 'г'),
    (gen_random_uuid(), 'Перец болгарский', 'г'),
    (gen_random_uuid(), 'Зелень укропа', 'г'),
    (gen_random_uuid(), 'Зелень петрушки', 'г'),
    (gen_random_uuid(), 'Рис', 'г'),
    (gen_random_uuid(), 'Гречка', 'г'),
    (gen_random_uuid(), 'Макароны', 'г'),
    (gen_random_uuid(), 'Томатная паста', 'г'),
    (gen_random_uuid(), 'Сода пищевая', 'ч.л.'),
    (gen_random_uuid(), 'Разрыхлитель', 'ч.л.')
ON CONFLICT (name) DO NOTHING;

INSERT INTO tags (id, name, category) VALUES
    (gen_random_uuid(), 'Вегетарианское', 'DIET'),
    (gen_random_uuid(), 'Веганское', 'DIET'),
    (gen_random_uuid(), 'Без глютена', 'DIET'),
    (gen_random_uuid(), 'Низкокалорийное', 'DIET'),
    (gen_random_uuid(), 'Высокобелковое', 'DIET'),
    (gen_random_uuid(), 'Русская кухня', 'CUISINE'),
    (gen_random_uuid(), 'Итальянская кухня', 'CUISINE'),
    (gen_random_uuid(), 'Азиатская кухня', 'CUISINE'),
    (gen_random_uuid(), 'Средиземноморская кухня', 'CUISINE'),
    (gen_random_uuid(), 'Домашняя кухня', 'CUISINE'),
    (gen_random_uuid(), 'Содержит глютен', 'ALLERGEN'),
    (gen_random_uuid(), 'Содержит лактозу', 'ALLERGEN'),
    (gen_random_uuid(), 'Содержит яйца', 'ALLERGEN'),
    (gen_random_uuid(), 'Содержит орехи', 'ALLERGEN'),
    (gen_random_uuid(), 'Содержит рыбу', 'ALLERGEN')
ON CONFLICT (name) DO NOTHING;
