UPDATE recipes SET image_url = 'local://dish_borscht' WHERE title = 'Борщ';
UPDATE recipes SET image_url = 'local://dish_kotlety' WHERE title = 'Котлеты по-домашнему';
UPDATE recipes SET image_url = 'local://dish_bliny' WHERE title = 'Блины';
UPDATE recipes SET image_url = 'local://dish_pelmeni' WHERE title = 'Пельмени';
UPDATE recipes SET image_url = 'local://dish_olivier' WHERE title = 'Салат Оливье';
UPDATE recipes SET image_url = 'local://dish_carbonara' WHERE title = 'Паста Карбонара';
UPDATE recipes SET image_url = 'local://dish_greek_salad' WHERE title = 'Греческий салат';
UPDATE recipes SET image_url = 'local://dish_teriyaki' WHERE title = 'Курица терияки';
UPDATE recipes SET image_url = 'local://dish_buckwheat' WHERE title = 'Гречневая каша с грибами';
UPDATE recipes SET image_url = 'local://dish_shashlik' WHERE title = 'Шашлык из курицы';
UPDATE recipes SET image_url = 'local://dish_risotto' WHERE title = 'Ризотто с грибами';
UPDATE recipes SET image_url = 'local://dish_syrniki' WHERE title = 'Сырники';
UPDATE recipes SET image_url = 'local://dish_pizza' WHERE title = 'Пицца Маргарита';
UPDATE recipes SET image_url = 'local://dish_salmon' WHERE title = 'Запечённый лосось';
UPDATE recipes SET image_url = 'local://dish_okroshka' WHERE title = 'Окрошка';
UPDATE recipes SET image_url = 'local://dish_tomyam' WHERE title = 'Том-ям';
UPDATE recipes SET image_url = 'local://dish_lasagna' WHERE title = 'Лазанья болоньезе';
UPDATE recipes SET image_url = 'local://dish_plov' WHERE title = 'Плов узбекский';
UPDATE recipes SET image_url = 'local://dish_omlet' WHERE title = 'Омлет';
UPDATE recipes SET image_url = 'local://dish_minestrone' WHERE title = 'Суп минестроне';
UPDATE recipes SET image_url = 'local://dish_guacamole' WHERE title = 'Гуакамоле';
UPDATE recipes SET image_url = 'local://dish_ramen' WHERE title = 'Рамен с курицей';
UPDATE recipes SET image_url = 'local://dish_tiramisu' WHERE title = 'Тирамису';
UPDATE recipes SET image_url = 'local://dish_napoleon' WHERE title = 'Торт Наполеон';
UPDATE recipes SET image_url = 'local://dish_chicken_soup' WHERE title = 'Куриный суп';
UPDATE recipes SET image_url = 'local://dish_fried_rice' WHERE title = 'Жареный рис по-азиатски';
